CREATE TABLE "StudioPageContent" (
    "id" TEXT NOT NULL,
    "eyebrow" TEXT NOT NULL,
    "eyebrowEn" TEXT,
    "title" TEXT NOT NULL,
    "titleEn" TEXT,
    "intro" TEXT NOT NULL,
    "introEn" TEXT,
    "founderOneName" TEXT NOT NULL,
    "founderOneNameEn" TEXT,
    "founderOneRole" TEXT NOT NULL,
    "founderOneRoleEn" TEXT,
    "founderOneDescription" TEXT NOT NULL,
    "founderOneDescriptionEn" TEXT,
    "founderOneImageUrl" TEXT NOT NULL,
    "founderOneImageAlt" TEXT,
    "founderOneImageAltEn" TEXT,
    "founderTwoName" TEXT NOT NULL,
    "founderTwoNameEn" TEXT,
    "founderTwoRole" TEXT NOT NULL,
    "founderTwoRoleEn" TEXT,
    "founderTwoDescription" TEXT NOT NULL,
    "founderTwoDescriptionEn" TEXT,
    "founderTwoImageUrl" TEXT NOT NULL,
    "founderTwoImageAlt" TEXT,
    "founderTwoImageAltEn" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StudioPageContent_pkey" PRIMARY KEY ("id")
);

INSERT INTO "StudioPageContent" (
    "id",
    "eyebrow",
    "title",
    "intro",
    "founderOneName",
    "founderOneRole",
    "founderOneDescription",
    "founderOneImageUrl",
    "founderOneImageAlt",
    "founderTwoName",
    "founderTwoRole",
    "founderTwoDescription",
    "founderTwoImageUrl",
    "founderTwoImageAlt",
    "updatedAt"
) VALUES (
    'studio',
    'Les fondateurs',
    'Deux regards, une même vision créative.',
    'Studio Volante est né de la rencontre de deux parcours complémentaires, unis par l''exigence du beau et la conviction que chaque marque a une histoire unique à raconter.',
    'William Romano',
    'Co-fondateur',
    'Stratège de marque et directeur artistique, William conçoit des univers visuels justes, durables et porteurs de sens. Il accompagne les marques dans la définition de leur identité et de leur direction créative.',
    '',
    'Portrait de William Romano',
    'Yasmine De Wilde',
    'Co-fondatrice',
    'Experte en stratégie de contenu et communication, Yasmine donne voix aux marques avec clarté et émotion. Elle structure les messages pour créer des récits authentiques et impactants.',
    '',
    'Portrait de Yasmine De Wilde',
    CURRENT_TIMESTAMP
);
